# Generated by Django 4.1.13 on 2024-05-10 14:56

import apps.questionnaires.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
                ('continent', models.CharField(choices=[('north_america', 'North America'), ('SOUTH_AMERICA', 'SOUTH AMERICA'), ('europe', 'Europe'), ('asia_pacific', 'Asia Pacific'), ('australia', 'Australia')], default='north_america', max_length=15, verbose_name='Continent')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_category',
            field=models.CharField(choices=[('experience_level', 'Experience Level'), ('budget', 'Budget'), ('components', 'Components'), ('priority_and_others', 'Priority & Others'), ('games_and_utility', 'Games & Utility'), ('location', 'Locations')], default='experience_level', max_length=19, verbose_name='Question Category'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='order',
            field=models.SmallIntegerField(default=0, help_text='If needed, this field can be used to specify the answers order.(Not Necessary)', verbose_name='Answer Order'),
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', apps.questionnaires.fields.LowercaseEmailField(max_length=254, verbose_name='Email Address')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'User Request',
                'verbose_name_plural': 'User Requests',
                'db_table': 'user_requests',
            },
        ),
    ]
